DB_beta: 0.9
DB_beta_sigma: 0
FAMO_w_gamma: 0.001
FAMO_w_lr: 0.025
FORUM_phi: 0.1
FairGrad_alpha: 1.0
GradVac_beta: 0.5
GradVac_group_type: 0
MoCo_beta: 0.5
MoCo_beta_sigma: 0.5
MoCo_gamma: 0.1
MoCo_gamma_sigma: 0.5
MoCo_rho: 0
MoDo_gamma: 0.001
MoDo_rho: 0.1
SDMGrad_lamda: 0.3
SDMGrad_niter: 20
STCH_mu: 1.0
STCH_warmup_epoch: 4
T: 2.0
UPGrad_norm_eps: 0.0001
UPGrad_reg_eps: 0.0001
alpha: 1.5
arch: HPS
calpha: 0.5
dilate_scale: 8
encoder_lr_factor: 0.1
end_factor: 1.0
ep_grad: 'False'
epochs: 200
eta_min: 1.0e-07
gamma: 0.5
img_size: 448
inner_lr: 0.1
inner_step: 5
kgamma: 1.0
leak: 0.0
load_path: null
max_norm: 1.0
mgda_gn: none
momentum: 0.9
multi_input: 'False'
num_experts: null
num_nonzeros: 2
num_workers: 2
optim: adamw
optim_niter: 20
outer_lr: 0.001
poly_power: 1.0
pretrained: true
rep_grad: false
rescale: 1
robust_step_size: 0.01
save_path: null
seed: 42
start_factor: 0.001
step_size: 100
test_bs: 12
train_bs: 12
update_weights_every: 1
warmup_epochs: 15
weighting: EW
global_scale: 1022
bbch_min: 10
bbch_max: 17
ppr_min: 0.0
ppr_max: 3.0
early_stopping: 200

